backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "news"
    label: "News"
    files:
      - name: "news"
        label: "News Eintr√§ge"
        file: "content/news.json"
        fields:
          - {label: "News Liste", name: "news", widget: "list", fields: [
              {label: "Datum", name: "date", widget: "string"},
              {label: "Titel", name: "title", widget: "string"},
              {label: "Text", name: "text", widget: "text"},
              {label: "Link", name: "link", widget: "string"},
              {label: "Link Text", name: "linkText", widget: "string"}
            ]}
